export interface UserInfo {
  now: number,
  mine: {
    id: number;
    app_id: number;
    area_id: number;
    nickname: string;
    avatar: string;
    mobile: string;
    openid: string;
    province: string;
    city: string;
    district: string;
    orders: number;
    orders_cancel: number;
    orders_done: number;
    expends: string;
    admin_switch: number;
    seller_switch: number;
    black_switch: number;
    createtime: number;
    updatetime: number;
    remark: string;
    invites: number;
    inviter_id: number;
    sells: number;
    sell_money: string;
    sell_income: string;
    sell_outcash: string;
    seller_id: number;
    seller_time: number;
    my_staff_id: number;
    _id: string;
    avatar_url: string;
  }
  statistic: {
    topays: number
    todos: number
  }
  staff: {
    id: number;
    app_id: number;
    area_id: number;
    user_id: number;
    openid: string;
    nickname: string;
    avatar: string;
    sex: string;
    age: number;
    mobile: string;
    realname: string;
    idcardnum: string;
    idcards_images: string;
    papers_images: string;
    odmanar: string;
    master: string;
    master_uid: number;
    subs: number;
    money: string;
    income: string;
    income_service: string;
    income_master: string;
    outcash: string;
    createtime: number;
    updatetime: number;
    status: string;
    status_time: number;
    status_remark: string;
    remark: string;
    stop_switch: number;
    sex_text: string;
    odmanar_text: string;
    master_text: string;
    status_text: string;
    status_time_text: string;
    avatar_url: string;
  }
}